# 指定该文件版本
version: '1'
# 把每个子目录视为一个镜像，开始构建
services:
  web:
    # 此处仅允许 image, build, ports，禁止其他字段出现，如果有 volume，cmd 等设置需求，请在 Dockerfile 里进行文件拷贝或者申明。
    image: boogipop/ezdouble
    build: .
    ports:
      - "9877:8000"
