/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClearCode: typeof import('./src/components/CodeEditor/ClearCode.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    CodePanel: typeof import('./src/components/CodePanel.vue')['default']
    CopyCode: typeof import('./src/components/CodeEditor/CopyCode.vue')['default']
    DownloadCode: typeof import('./src/components/CodeEditor/DownloadCode.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    InputPanel: typeof import('./src/components/InputPanel.vue')['default']
    OutputPanel: typeof import('./src/components/OutputPanel.vue')['default']
    ProblemPanel: typeof import('./src/components/ProblemPanel.vue')['default']
    UploadForm: typeof import('./src/components/UploadForm.vue')['default']
  }
}
